name: C/C++ CI

on:
  push

#https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions


jobs:
  
  build:

    runs-on: [self-hosted, windows]
    
    defaults:
      run:
        shell: cmd

    steps:
    
      - name: Some Gitinfo
        run: |
            echo "The event name is ${{ github.ref }}"
            set mystr=${{github.ref}}
            echo %mystr%
            set mystr=%mystr:~11,100%
            echo %mystr%
    
      - name: Get Env
        run: |
            SET
        
      - name: Repository Setup
        run: |
            set gitbranch=${{github.ref}}
            set gitbranch=%gitbranch:~11,100%
            set fallbackBranch=feature/UnitTests
            
            rmdir /S /Q ClearCore_Arduino
            git clone -b "%gitbranch%" https://git-server.teknic.com/CustomerPackages/ClearCore_Arduino.git || (git clone -b "%fallbackBranch%" https://git-server.teknic.com/CustomerPackages/ClearCore_Arduino.git)
            cd ClearCore_Arduino/
            rmdir /S /Q Teknic
            git clone -b "%gitbranch%" https://github.com/Teknic-Inc/ClearCore-library.git Teknic || (git clone -b "%fallbackBranch%" https://github.com/Teknic-Inc/ClearCore-library.git Teknic)
            mkdir variants\clearcore\Third Party
            git clone -b master https://git-server.teknic.com/CustomerPackages/same53.git "variants\clearcore\Third Party\same53"
            
      # - name: Test Script
        # run: | 
            # cd ClearCore_Arduino/
            # Teknic\UnitTests\TestScripts\TestScript.py
